// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ7n1CZAHTDKq2yJGFmEdTiQquDtL4zSU',
    appId: '1:183685754520:web:deed52d8fff3c3224f6aed',
    messagingSenderId: '183685754520',
    projectId: 'fir-rsvp-flutter',
    authDomain: 'fir-rsvp-flutter.firebaseapp.com',
    storageBucket: 'fir-rsvp-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3PlrrEn3cL7V0On0q9QGMFZcq0nevcjo',
    appId: '1:183685754520:ios:d48b30a13b9e4a164f6aed',
    messagingSenderId: '183685754520',
    projectId: 'fir-rsvp-flutter',
    storageBucket: 'fir-rsvp-flutter.firebasestorage.app',
    iosBundleId: 'com.example.firebaseRsvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3PlrrEn3cL7V0On0q9QGMFZcq0nevcjo',
    appId: '1:183685754520:ios:d48b30a13b9e4a164f6aed',
    messagingSenderId: '183685754520',
    projectId: 'fir-rsvp-flutter',
    storageBucket: 'fir-rsvp-flutter.firebasestorage.app',
    iosBundleId: 'com.example.firebaseRsvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ7n1CZAHTDKq2yJGFmEdTiQquDtL4zSU',
    appId: '1:183685754520:web:e88704699a2dc7924f6aed',
    messagingSenderId: '183685754520',
    projectId: 'fir-rsvp-flutter',
    authDomain: 'fir-rsvp-flutter.firebaseapp.com',
    storageBucket: 'fir-rsvp-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsD0bV7A4sjVbC2ysfZLUnQJMB7GOp2uM',
    appId: '1:183685754520:android:637648d2498391d34f6aed',
    messagingSenderId: '183685754520',
    projectId: 'fir-rsvp-flutter',
    storageBucket: 'fir-rsvp-flutter.firebasestorage.app',
  );

}